"""Export locally stored NHK EASY articles to Anki decks (.apkg)."""

from __future__ import annotations

import hashlib
import zipfile
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Any, Literal

from nhk_easy_fetcher.errors import AnkiExportError
from nhk_easy_fetcher.models import ArticleRecord, ContentStatus, Paragraph

PERSONAL_USE_NOTICE = "NHK content — personal study only, do not redistribute."
DECK_DESCRIPTION = (
    "Generated by nhk-easy-fetcher from locally saved NHK NEWS WEB EASY articles. "
    "NHK content is for personal study only — do not redistribute, mirror, or share "
    "these decks publicly."
)

FuriganaMode = Literal["plain", "readings"]


@dataclass(frozen=True)
class ExportSummary:
    deck_path: Path
    deck_name: str
    article_count: int
    card_count: int
    articles: list[str]


def _require_genanki() -> Any:
    try:
        import genanki  # type: ignore[import-untyped]
    except ImportError as exc:
        raise AnkiExportError(
            "genanki is required for APKG export. Install with: pip install -e '.[anki]'"
        ) from exc
    return genanki


def _stable_id(seed: str) -> int:
    digest = hashlib.sha256(seed.encode()).hexdigest()
    return int(digest[:15], 16)


def _paragraph_front(paragraph: Paragraph, furigana: FuriganaMode) -> str:
    if furigana == "readings":
        return paragraph.with_readings
    return paragraph.plain


def _paragraph_back(article: ArticleRecord, paragraph: Paragraph, index: int) -> str:
    lines = [
        paragraph.plain,
        "",
        f"Article: {article.article_id}",
        f"Paragraph: {index + 1}/{len(article.paragraphs)}",
        f"Source: {article.source_url}",
        "",
        PERSONAL_USE_NOTICE,
    ]
    return "\n".join(lines)


def _find_audio_file(article_dir: Path, article: ArticleRecord) -> Path | None:
    if article.audio.status != "available":
        return None
    candidates = ["audio.m4a", "audio.mp3"]
    if article.audio.format:
        preferred = f"audio.{article.audio.format}"
        candidates = [preferred] + [name for name in candidates if name != preferred]
    for name in candidates:
        path = article_dir / name
        if path.is_file():
            return path
    return None


def load_article(article_dir: Path) -> ArticleRecord:
    json_path = article_dir / "article.json"
    if not json_path.is_file():
        raise AnkiExportError(f"No article.json in {article_dir}")
    return ArticleRecord.model_validate_json(json_path.read_text(encoding="utf-8"))


def discover_article_dirs(
    articles_root: Path,
    *,
    since: date | None = None,
    until: date | None = None,
) -> list[Path]:
    if not articles_root.is_dir():
        return []

    discovered: list[tuple[datetime | None, Path]] = []
    for json_path in sorted(articles_root.rglob("article.json")):
        article_dir = json_path.parent
        try:
            article = load_article(article_dir)
        except AnkiExportError:
            continue
        if article.content_status != ContentStatus.COMPLETE:
            continue
        if since is not None or until is not None:
            published = article.published_at
            if published is None:
                continue
            published_date = published.date()
            if since is not None and published_date < since:
                continue
            if until is not None and published_date > until:
                continue
        discovered.append((article.published_at, article_dir))

    discovered.sort(key=lambda item: (item[0] is None, item[0] or datetime.min, str(item[1])))
    return [article_dir for _, article_dir in discovered]


def _build_notes(
    article: ArticleRecord,
    article_dir: Path,
    *,
    furigana: FuriganaMode,
    include_audio: bool,
    model: Any,
    genanki: Any,
) -> tuple[list[Any], list[str]]:
    notes: list[Any] = []
    media_files: list[str] = []
    audio_path = _find_audio_file(article_dir, article) if include_audio else None
    audio_field = ""
    if audio_path is not None:
        audio_field = f"[sound:{audio_path.name}]"
        media_files.append(str(audio_path))

    for index, paragraph in enumerate(article.paragraphs):
        paragraph_audio = audio_field if index == 0 and audio_field else ""
        note = genanki.Note(
            model=model,
            fields=[
                _paragraph_front(paragraph, furigana),
                _paragraph_back(article, paragraph, index),
                paragraph_audio,
            ],
            guid=f"{article.article_id}-p{index + 1}",
        )
        notes.append(note)

    return notes, media_files


def export_apkg(
    article_dirs: list[Path],
    *,
    deck_name: str,
    output_path: Path,
    furigana: FuriganaMode = "readings",
    include_audio: bool = False,
) -> ExportSummary:
    if not article_dirs:
        raise AnkiExportError("No complete articles to export")

    genanki = _require_genanki()
    model = genanki.Model(
        _stable_id("nhk-easy-fetcher-paragraph-v1"),
        "NHK EASY Paragraph",
        fields=[
            {"name": "Front"},
            {"name": "Back"},
            {"name": "Audio"},
        ],
        templates=[
            {
                "name": "Paragraph",
                "qfmt": "{{Front}}{{#Audio}}<br>{{Audio}}{{/Audio}}",
                "afmt": "{{FrontSide}}<hr id='answer'>{{Back}}",
            }
        ],
        css=".card { font-family: sans-serif; font-size: 20px; }",
    )
    deck = genanki.Deck(_stable_id(f"nhk-easy-fetcher:{deck_name}"), deck_name)
    deck.description = DECK_DESCRIPTION

    all_media: list[str] = []
    card_count = 0
    exported_ids: list[str] = []

    for article_dir in article_dirs:
        article = load_article(article_dir)
        if article.content_status != ContentStatus.COMPLETE:
            raise AnkiExportError(
                f"Article {article.article_id} is not complete "
                f"(status={article.content_status.value})"
            )
        if not article.paragraphs:
            raise AnkiExportError(f"Article {article.article_id} has no paragraphs")

        notes, media_files = _build_notes(
            article,
            article_dir,
            furigana=furigana,
            include_audio=include_audio,
            model=model,
            genanki=genanki,
        )
        for note in notes:
            deck.add_note(note)
        all_media.extend(media_files)
        card_count += len(notes)
        exported_ids.append(article.article_id)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    package = genanki.Package(deck, media_files=sorted(set(all_media)))
    package.write_to_file(str(output_path))
    if not _is_valid_apkg(output_path):
        raise AnkiExportError(f"Failed to write a valid APKG file at {output_path}")

    return ExportSummary(
        deck_path=output_path,
        deck_name=deck_name,
        article_count=len(article_dirs),
        card_count=card_count,
        articles=exported_ids,
    )


def default_deck_output_dir(output_dir: Path) -> Path:
    return output_dir.expanduser().resolve() / ".nhk-easy-fetcher" / "anki"


def default_deck_path(output_dir: Path, deck_name: str) -> Path:
    safe_name = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in deck_name)
    return default_deck_output_dir(output_dir) / f"{safe_name}.apkg"


def _is_valid_apkg(path: Path) -> bool:
    if not path.is_file() or path.stat().st_size == 0:
        return False
    try:
        with zipfile.ZipFile(path) as archive:
            return "collection.anki2" in archive.namelist()
    except zipfile.BadZipFile:
        return False
